version: "3"

services:
  jekyll:
    container_name: jekyll
    platform: linux/amd64
    tty: true
    volumes:
      - ./:/app
    build: .
    restart: unless-stopped
    ports:
      - "4000:4000"
